[package]
name = "skill_passport"
version = "1.0.0"
authors = ["Your Name <your.email@example.com>"]

[addresses]
skill_passport_addr = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
